# Generated by Django 2.1.5 on 2019-01-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eighthrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkDay',
        ),
    ]
